const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const script = fs.readFileSync(require('node:path').join(__dirname, '../src/workspace-card.html'), 'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
class Element {
  constructor() { this.scrollTop=0; this.scrollHeight=200; this.clientHeight=200; this.childNodes=[]; this.textContent=''; this.value=''; this.style={}; this.hidden=false; this.classList={toggle:()=>false}; }
  append(...nodes) { this.childNodes.push(...nodes); }
  replaceChildren(...nodes) { this.childNodes=nodes; }
  setAttribute() {}
  get text() { return this.textContent+this.childNodes.map(n=>n.text).join(''); }
}
function harness(openai) {
 const elements=new Map(), listeners={}, timers=new Map(), sent=[]; let sequence=0;
 const parent={postMessage:m=>sent.push(m)};
 const window={parent,openai,addEventListener:(name,fn)=>listeners[name]=fn};
 const context={window,document:{body:new Element(),documentElement:{scrollHeight:500},getElementById:id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id)},createElement:()=>new Element()},matchMedia:()=>({matches:false}),navigator:{clipboard:{writeText:async()=>{}}},setTimeout:(fn,ms)=>{const id=++sequence;timers.set(id,{fn,ms});return id},clearTimeout:id=>timers.delete(id)};
 vm.runInNewContext(script,context);
 const emit=(method,params)=>listeners.message({source:parent,data:{jsonrpc:'2.0',method,params}});
 const respond=(request,result,error)=>listeners.message({source:parent,data:{jsonrpc:'2.0',id:request.id,result,error}});
 const flush=()=>new Promise(resolve=>setImmediate(resolve));
 return {elements,sent,timers,emit,respond,flush,globals:value=>listeners["openai:set_globals"]({detail:{globals:value}}),get:id=>elements.get(id),result:data=>emit('ui/notifications/tool-result',{structuredContent:data}),async ready(){respond(sent.find(m=>m.method==='ui/initialize'),{hostContext:{theme:'light'}});await flush()},async tick(){const entry=[...timers.entries()].find(([,t])=>t.ms===2000);assert.ok(entry,'expected refresh timer');timers.delete(entry[0]);entry[1].fn();await flush()},refreshCount:()=>[...timers.values()].filter(t=>t.ms===2000).length};
}
const command=(overrides={})=>({tool:'exec_command',result:{session_id:'one',running:true,command:'build',elapsed_seconds:2,output:'first\n',full_output:'first\n',...overrides}});
test('tool input shows progress and cancellation stops automatic updates',async()=>{const h=harness();await h.ready();h.emit('ui/notifications/tool-input',{arguments:{command:'build'}});assert.equal(h.get('badge').textContent,'执行中');h.result(command());assert.equal(h.refreshCount(),1);h.emit('ui/notifications/tool-cancelled',{});assert.equal(h.get('badge').textContent,'已取消');assert.equal(h.refreshCount(),0);assert.equal(h.get('stop').hidden,true)});
test('automatic reads use snapshots and finish without duplicate or consumed output',async()=>{const h=harness();await h.ready();h.result(command());await h.tick();let call=h.sent.at(-1);assert.equal(call.params.name,'read_command');assert.equal(call.params.arguments.session_id,'one');h.respond(call,{structuredContent:{tool:'read_command',result:{session_id:'one',running:true,output_mode:'snapshot',output:'first\nsecond\n',elapsed_seconds:4}}});await h.flush();assert.equal(h.get('body').text.split('first').length-1,1);await h.tick();call=h.sent.at(-1);h.respond(call,{structuredContent:{tool:'read_command',result:{session_id:'one',running:false,output_mode:'snapshot',output:'first\nsecond\ndone',exit_code:0,elapsed_seconds:6}}});await h.flush();assert.equal(h.get('badge').textContent,'完成');assert.equal(h.refreshCount(),0);assert.ok(h.get('body').text.includes('done'));assert.ok(!h.sent.some(m=>m.params?.name==='poll_command'))});
test('command failure and timeout retain output',async()=>{for(const timed_out of [false,true]){const h=harness();await h.ready();h.result({...command({running:false,exit_code:1,timed_out,full_output:'compiler failed'}),isError:true});assert.ok(h.get('body').text.includes('compiler failed'));assert.equal(h.get('badge').textContent,timed_out?'超时':'失败');assert.equal(h.refreshCount(),0)}});
test('bridge failure pauses refresh and stale reads cannot replace another result',async()=>{const h=harness();await h.ready();h.result(command());await h.tick();h.respond(h.sent.at(-1),null,{message:'offline'});await h.flush();assert.equal(h.refreshCount(),0);assert.ok(h.get('foot').textContent.includes('offline'));h.result(command());await h.tick();const old=h.sent.at(-1);h.result({tool:'read_file',result:{path:'a.ts',lines:['1: current file']}});h.respond(old,{structuredContent:command({output:'stale'})});await h.flush();assert.equal(h.get('title').textContent,'阅读文件');assert.equal(h.refreshCount(),0)});
test('stop executes only after user clicks and status refresh remains manual',async()=>{const h=harness();await h.ready();h.result(command());assert.ok(!h.sent.some(m=>m.params?.name==='stop_command'));const click=h.get('stop').onclick();const call=h.sent.at(-1);assert.equal(call.params.name,'stop_command');h.respond(call,{structuredContent:{tool:'stop_command',result:{session_id:'one',running:false,stopped:true,exit_code:0,output_mode:'snapshot',output:'stopped'}}});await click;assert.equal(h.get('badge').textContent,'已停止');assert.equal(h.refreshCount(),0);h.result({tool:'get_workspace_status',result:{version:'1',tool_count:2,running_commands:0,tools:['read_file','read_command'],activity:[]}});assert.equal(h.refreshCount(),0);const refresh=h.get('more').onclick();const req=h.sent.at(-1);assert.equal(req.params.name,'get_workspace_status');h.respond(req,{structuredContent:{tool:'get_workspace_status',result:{version:'1',tool_count:2,running_commands:0}}});await refresh});

test('preview host inline scripts compile',()=>{const html=fs.readFileSync(require('node:path').join(__dirname,'card-host.html'),'utf8');const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];assert.ok(scripts.length);for(const [,source] of scripts)assert.doesNotThrow(()=>new vm.Script(source))});
test('stdin snapshots retain command progress and Git failures retain output',async()=>{const h=harness();await h.ready();h.result({...command(),tool:'write_stdin'});assert.equal(h.get('title').textContent,'发送命令输入');assert.equal(h.refreshCount(),1);h.result({tool:'git_diff',isError:true,result:{output:'fatal: not a repository',exit_code:128}});assert.ok(h.get('body').text.includes('fatal: not a repository'));assert.equal(h.get('badge').textContent,'失败');assert.equal(h.refreshCount(),0)});

test('workspace instructions and plans show actual guidance and progress',async()=>{const h=harness();await h.ready();h.result({tool:'open_workspace',result:{path:'workspace',version:'1.3.0',instructions:[{path:'AGENTS.md',content:'project instruction',truncated:true}],plan:[]}});assert.ok(h.get('body').text.includes('project instruction'));assert.ok(h.get('body').text.includes('内容已截断'));const plan=[{step:'inspect',status:'completed'},{step:'verify',status:'in_progress'}];h.result({tool:'update_plan',result:{path:'workspace',plan,explanation:'reason'}});assert.ok(h.get('meta').textContent.includes('1 / 2'));assert.ok(h.get('body').text.includes('进行中'));h.result({tool:'get_workspace_status',result:{plans:[{path:'workspace',plan,explanation:'reason'}]}});assert.ok(h.get('body').text.includes('执行计划 · workspace'));assert.ok(h.get('body').text.includes('verify'))});
test('partial patch failure shows both error and real changed files',async()=>{const h=harness();await h.ready();h.result({tool:'apply_patch',isError:true,result:{partial:true,message:'disk commit failed',files:[{path:'actual.ts',operation:'update',diff:{added:1,removed:0,rows:[{kind:'add',new_line:1,text:'actual change'}]}}]}});assert.equal(h.get('badge').textContent,'部分应用');assert.ok(h.get('body').text.includes('disk commit failed'));assert.ok(h.get('body').text.includes('actual.ts'));assert.ok(h.get('body').text.includes('actual change'))});
test('output follows the tail only when user was near the bottom',async()=>{const h=harness();await h.ready();h.result(command());const body=h.get('body');body.scrollHeight=1000;body.clientHeight=200;body.scrollTop=800;h.result(command());assert.equal(body.scrollTop,1000);body.scrollTop=150;h.result({...command({full_output:'more output'}),tool:'read_command'});assert.equal(body.scrollTop,150)});
test('expired command sessions show recovery guidance and stop polling',async()=>{const h=harness();await h.ready();h.result(command());h.result({tool:'read_command',isError:true,result:{error_code:'INVALID_ARGUMENT',message:'Unknown or expired session_id'}});assert.ok(h.get('body').text.includes('旧会话不可恢复'));assert.ok(h.get('body').text.includes('INVALID_ARGUMENT'));assert.equal(h.refreshCount(),0);assert.equal(h.get('stop').hidden,true)});

test('plan badge reflects progress and workspace accepts actual nested plan and shell shapes',async()=>{const h=harness();await h.ready();for(const [plan,badge] of [[[ {step:'first',status:'completed'},{step:'next',status:'in_progress'} ],'进行中'],[[{step:'done',status:'completed'}],'已完成'],[[{step:'later',status:'pending'}],'待进行'],[[],'待进行']]){h.result({tool:'update_plan',result:{plan}});assert.equal(h.get('badge').textContent,badge)}h.result({tool:'open_workspace',result:{version:'1.3.0',shells:[{name:'powershell',available:true,path:'shell.exe'},{name:'bash',available:false,path:null}],plan:{path:'workspace',explanation:'nested reason',plan:[{step:'nested task',status:'in_progress'}]}}});assert.ok(h.get('body').text.includes('nested task'));assert.ok(h.get('body').text.includes('nested reason'));assert.ok(h.get('body').text.includes('powershell（可用） shell.exe'));assert.ok(h.get('body').text.includes('bash（不可用）'))});

test('cmd input and actual shell are visible',async()=>{const h=harness();await h.ready();h.emit('ui/notifications/tool-input',{arguments:{cmd:'printf hello'}});assert.ok(h.get('body').text.includes('printf hello'));h.result(command({shell:'git_bash'}));assert.ok(h.get('meta').text.includes('git_bash'))});
test('restores direct and nested host metadata without toolOutput',async()=>{for(const metadata of [{mcp_tool_result:{structuredContent:{tool:'read_file',result:{path:'restored.txt',lines:['1: restored'],returned_count:1}}}},{call_tool_result:{mcp_tool_result:{structuredContent:{tool:'read_file',result:{path:'restored.txt',lines:['1: restored'],returned_count:1}}}}}]){const h=harness({toolResponseMetadata:metadata});assert.ok(h.get('body').text.includes('restored'));assert.equal(h.get('badge').textContent,'完成');const init=h.sent.find(x=>x.method==='ui/initialize');h.respond(init,null,{message:'Legacy host'});await h.flush();assert.equal(h.get('foot').textContent,'以上为实际工具结果')}});
test('late globals preserve metadata images and can supersede earlier output',async()=>{const h=harness({toolOutput:{tool:'read_file',result:{path:'old.txt',lines:['1: old'],returned_count:1}}});h.globals({toolResponseMetadata:{mcp_tool_result:{structuredContent:{tool:'read_image',result:{path:'pixel.png',mime_type:'image/png',size_bytes:3}},content:[{type:'image',mimeType:'image/png',data:'YWJj'}]}}});assert.equal(h.get('path').textContent,'pixel.png');assert.equal(h.get('body').childNodes[0].src,'data:image/png;base64,YWJj');h.globals({theme:'dark'});assert.equal(h.get('path').textContent,'pixel.png')});
test('legacy interactive bridge sends one call and unwraps its receipt',async()=>{let calls=0;const h=harness({toolOutput:{tool:'get_workspace_status',result:{version:'1.4.1',tool_count:22}},callTool:async()=>{calls++;return {mcp_tool_result:{structuredContent:{tool:'get_workspace_status',result:{version:'1.4.1',tool_count:22,running_commands:3}}}}}});await h.get('more').onclick();assert.equal(calls,1);assert.ok(h.get('meta').text.includes('3 个运行中命令'))});

const liveSnapshot=(extra={})=>({tool:'render_workspace',result:{path:'E:/workspace',version:'1.5.0',instance_id:'instance-a',checked_at:'2026-09-16T09:00:00Z',activity:[],commands:[],plans:[],ui:{viewers:[]},...extra}});
test('live panel polls across tools and idle periods without declaring completion',async()=>{const h=harness();await h.ready();h.result(liveSnapshot());assert.equal(h.get('badge').textContent,'观察中');assert.equal(h.refreshCount(),1);await h.tick();const req=h.sent.at(-1);assert.equal(req.params.name,'read_workspace_activity');assert.equal(req.params.arguments.bridge,'standard');assert.ok(req.params.arguments.viewer_id);h.respond(req,{structuredContent:liveSnapshot({activity:[{id:'one',tool:'read_file',status:'running',target:'E:/workspace/a.txt',elapsed_ms:24}],plans:[{plan:[{step:'verify',status:'in_progress'}]}]})});await h.flush();assert.equal(h.get('badge').textContent,'执行中');assert.ok(h.get('body').text.includes('阅读文件'));assert.ok(h.get('body').text.includes('verify'));assert.equal(h.refreshCount(),1);assert(!h.sent.some(x=>x.params?.name==='poll_command'))});
test('live pause and stale results do not stop tasks or overwrite a new card',async()=>{const h=harness();await h.ready();h.result(liveSnapshot());h.get('live-pause').onclick();assert.equal(h.refreshCount(),0);assert.ok(h.get('foot').textContent.includes('任务继续运行'));assert(!h.sent.some(x=>x.params?.name==='stop_command'));h.globals({theme:'dark'});assert.equal(h.get('badge').textContent,'已暂停');h.get('live-pause').onclick();const req=h.sent.at(-1);h.result({tool:'read_file',result:{path:'current',lines:['1: retain']}});h.respond(req,{structuredContent:liveSnapshot()});await h.flush();assert.equal(h.get('title').textContent,'阅读文件')});
test('live disconnect and instance replacement pause with explicit recovery',async()=>{const h=harness();await h.ready();h.result(liveSnapshot());await h.tick();h.respond(h.sent.at(-1),null,{message:'offline'});await h.flush();assert.equal(h.refreshCount(),0);assert.ok(h.get('foot').textContent.includes('offline'));h.get('live-pause').onclick();h.respond(h.sent.at(-1),{structuredContent:liveSnapshot({instance_id:'instance-b'})});await h.flush();assert.equal(h.refreshCount(),0);assert.ok(h.get('foot').textContent.includes('实例已改变'));h.get('live-pause').onclick();h.respond(h.sent.at(-1),{structuredContent:liveSnapshot({instance_id:'instance-b'})});await h.flush();assert.equal(h.refreshCount(),1)});
test('late live refresh cannot restart polling after host cancellation',async()=>{const h=harness();await h.ready();h.result(liveSnapshot());await h.tick();const req=h.sent.at(-1);h.emit('ui/notifications/tool-cancelled',{});h.respond(req,{structuredContent:liveSnapshot()});await h.flush();assert.equal(h.refreshCount(),0);assert.equal(h.get('badge').textContent,'已取消')});
test('legacy live panel restores, polls and feature-detects picture in picture',async()=>{let calls=[];const h=harness({toolOutput:liveSnapshot().result,requestDisplayMode:async({mode})=>({mode}),callTool:async(name,args)=>{calls.push({name,args});return {structuredContent:liveSnapshot()}}});h.result(liveSnapshot());assert.equal(h.get('live-pip').hidden,false);await h.get('live-pip').onclick();assert.equal(h.get('live-pip').textContent,'返回聊天');await h.tick();assert.equal(calls.length,1);assert.equal(calls[0].args.bridge,'legacy');assert.equal(calls[0].args.display_mode,'pip')});
